[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:node]
command=node --disable-warning=DEP0040 /app/dist/server.js
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
environment=NODE_ENV=production

[program:python]
command=/app/venv/bin/uvicorn main:app --host 0.0.0.0 --port 8501
directory=/app/python
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
